import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Home/Header/Header";

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: "--font-poppins",
  subsets: ['latin'],
});

export const metadata = {
  title: "Websoldier Abir",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/129941899_1526104271113036_5716203448165447673_n-modified.ico" />
      </head>
      <body className={`${poppins.variable}`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
